# Используем официальный образ Node.js
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY package.json ./
RUN npm install

# Копируем сам скрипт
COPY ttlinker.js ./

# Открываем нужный порт для WebSocket (если сервер работает локально)
EXPOSE 8098

# Запуск скрипта
CMD ["node", "ttlinker.js"]