FROM oven/bun:alpine AS builder
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install
COPY . .
RUN rm -rf /root/.cache

FROM oven/bun:alpine
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 8098
CMD ["bun", "ttlinker.js"]