version: '3.8'

services:
  telegram-api-server:
    image: ghcr.io/lukaszraczylo/tdlib-telegram-bot-api-docker/telegram-api-server:latest
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    ports:
      - "8081:8081"
    networks:
      - app-network

  tgbot:
    build: ./tgbot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
#      - PORT=9120 # custom port set
      - TGSERVER_HOST=telegram-api-server
      - TGSERVER_PORT=8081
    ports:
      - "8098:8098"  # custom port set
    volumes:
      - contentdownloads:/app/downloads
    depends_on:
      - telegram-api-server
    networks:
      - app-network

  tiktok-linker:
    build: ./tiktok-linker
    environment:
#      - PORT=9120  # custom port set
    depends_on:
      - tgbot
    networks:
      - app-network

  instagram-linker:
    build: ./instagram-linker
    environment:
      - IG_USERNAME=${IG_USERNAME}
      - IG_PASSWORD=${IG_PASSWORD}
#      - PORT=9120  # custom port set
    depends_on:
      - tgbot
    networks:
      - app-network

  youtube-linker:  
    build: ./youtube-linker
    environment:
#      - PORT=9120 # custom port set
    depends_on:
      - tgbot
    volumes:
      - contentdownloads:/app/downloads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  contentdownloads: