version: '3.8'

services:
  tgbot:
    image: tgbot:latest
    build:
      context: ./tgbot
      dockerfile: dockerfile
    pull_policy: build 
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "8098:8098"
    networks:
      - tiktok-network

  tiktok-linker:
    image: tiktok-downloader:latest
    build:
      context: ./ttlinker
      dockerfile: dockerfile
    pull_policy: build
    depends_on:
      - tgbot
    networks:
      - tiktok-network

networks:
  tiktok-network:
    driver: bridge