version: '3.8'

services:
  tgbot:
    image: tgbot
    build:
      context: ./tgbot
      dockerfile: dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "8098:8098"
    networks:
      - tiktok-network

  tiktok-downloader:
    image: tiktok-downloader
    build:
      context: ./ttlinker
      dockerfile: dockerfile
    depends_on:
      - tgbot
    networks:
      - tiktok-network

networks:
  tiktok-network:
    driver: bridge