version: '3.8'

services:
  tgbot:
    image: hehehol33/owndownloaderbot:tgbot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "8098:8098"
    networks:
      - app-network

  tiktok-linker:
    image: hehehol33/owndownloaderbot:tiktok-linker
    depends_on:
      - tgbot
    networks:
      - app-network

  instagram-linker:
    image: hehehol33/owndownloaderbot:instagram-linker
    depends_on:
      - tgbot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
