version: '3.8'

services:
  tgbot:
    image: hehehol33/owndownloaderbot:tgbot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=9120 # custom port set
    ports:
      - "9120:8098"  # custom port set
    networks:
      - app-network

  tiktok-linker:
    image: hehehol33/owndownloaderbot:tiktok-linker
    environment:
      - PORT=9120  # custom port set
    depends_on:
      - tgbot
    networks:
      - app-network

  instagram-linker:
    image: hehehol33/owndownloaderbot:instagram-linker
    environment:
      - IG_USERNAME=${IG_USERNAME}
      - IG_PASSWORD=${IG_PASSWORD}
      - PORT=9120  # custom port set
    depends_on:
      - tgbot
    networks:
      - app-network

  youtube-linker:  
    image: hehehol33/owndownloaderbot:ytlinker
    environment:
      - PORT=9120 # custom port set
    depends_on:
      - tgbot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
