version: '3.8'

services:
  tgbot:
    image: tgbot:latest
    build:
      context: ./tgbot
      dockerfile: dockerfile
    pull_policy: build 
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "8098:8098"
    networks:
      - app-network

  tiktok-linker:
    image: tiktok-downloader:latest
    build:
      context: ./ttlinker
      dockerfile: dockerfile
    pull_policy: build
    depends_on:
      - tgbot
    networks:
      - app-network

  instagram-linker:
    image: instagram-linker:latest
    build:
      context: ./iglinker
      dockerfile: dockerfile
    pull_policy: build
    depends_on:
      - tgbot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
