version: '3.8'

services:
  tgbot:
    image: hehehol33/owndownloaderbot:tgbot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=9120  # 
    ports:
      - "9120:9120"  # 
    networks:
      - app-network

  tiktok-linker:
    image: hehehol33/owndownloaderbot:tiktok-linker
    environment:
      - PORT=9120  # 
    depends_on:
      - tgbot
    networks:
      - app-network

  instagram-linker:
    image: hehehol33/owndownloaderbot:instagram-linker
    environment:
      - PORT=9120  # 
    depends_on:
      - tgbot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
