# ---------- Build stage ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src
    
# Copy csproj and restore dependencies (cache layer)
COPY *.csproj ./
RUN dotnet restore --disable-parallel --no-cache
    
# Copy the rest of the source code and publish
COPY . .
RUN dotnet publish TikTok-bot.csproj -c Release \
    -o /app/publish \
    --no-restore \
    -p:PublishTrimmed=true \
    -p:PublishSingleFile=false \
    -p:TrimMode=link \
    -r linux-musl-x64

    
# ---------- Runtime stage ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime
WORKDIR /app
    
# Copy published output from build stage
COPY --from=build /app/publish ./
    
# Expose port and set entrypoint
EXPOSE 8098
ENTRYPOINT ["dotnet", "TikTok-bot.dll"]